theme = "sonokai"

[editor]
line-number = "relative"
shell = ["zsh", "-c"]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = true

[keys.normal]
C-g = [":sh shpool detach"]
C-p = ["half_page_up"]
C-n = ["half_page_down"]

[keys.normal."C-w"]
b = ":buffer-close"
